"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django_auth_ldap.config import LDAPSearch
import ldap


# O backend do LDAP vem primeiro, para ser tentado antes do login local
AUTHENTICATION_BACKENDS = [
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# 1. Aponta para o container 'ldap-server' do docker-compose
AUTH_LDAP_SERVER_URI = "ldap://ldap-server:389"

# 2. (AD-SPECIFIC - Desabilitados para o teste local)
#    Quando for para produção, você vai descomentar estas linhas
# -----------------------------------------------------------------
# AUTH_LDAP_CONNECTION_OPTIONS = { ldap.OPT_REFERRALS: 0 }
# AUTH_LDAP_USER_DN_TEMPLATE = "%(user)s@bndes.gov.br"
# AUTH_LDAP_USER_SEARCH = LDAPSearch(
#     "DC=bndes,DC=gov,DC=br",
#     ldap.SCOPE_SUBTREE,
#     "(sAMAccountName=%(user)s)"
# )
# -----------------------------------------------------------------


# 3. Configurações para o nosso OpenLDAP local (MODO TESTE)
#    Vamos usar um template para construir o DN do usuário diretamente
AUTH_LDAP_USER_DN_TEMPLATE = "uid=%(user)s,ou=people,dc=bndes,dc=gov,dc=br"


# 4. Mapeamento (Funciona para ambos os modos)
#    Cria ou atualiza o usuário no Django com dados vindos do LDAP
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}

# (Opcional) Popula os campos 'is_staff' e 'is_superuser'
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
     "is_staff": "cn=django_staff,ou=groups,dc=bndes,dc=gov,dc=br",
     "is_superuser": "cn=django_admins,ou=groups,dc=bndes,dc=gov,dc=br",
 }

# Salva as alterações do AD no banco do Django
AUTH_LDAP_ALWAYS_UPDATE_USER = True

# --- FIM DA CONFIGURAÇÃO LDAP ---

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# (Para produção, isso deve vir de uma variável de ambiente)
SECRET_KEY = 'django-insecure-tfer#fiak(6ovma0c+*u45(3_j4a#*&16rn52hp62nei&f063-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Permite que o Docker acesse a aplicação
ALLOWED_HOSTS = ['*']  # <-- ALTERADO


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Nossos Apps
    'assistente',           # <-- ADICIONADO (Nosso app principal)
    'rest_framework',       # <-- ADICIONADO (Para a API)
    'django_celery_results',# <-- ADICIONADO (Para o Celery)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# --- CONFIGURAÇÃO DO POSTGRESQL (LÊ DO .ENV) ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': 'db',  # O nome do serviço no docker-compose.yml
        'PORT': '5432',
    }
}
# --- FIM DA CONFIGURAÇÃO DO POSTGRESQL ---


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'  # <-- ALTERADO

TIME_ZONE = 'America/Sao_Paulo'  # <-- ALTERADO

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Diretório onde o `collectstatic` irá jogar os arquivos (não usaremos agora)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Diretórios onde o Django vai PROCURAR por arquivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / "static", # Aponta para a pasta 'static' que criamos na raiz
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CONFIGURAÇÃO DO CELERY ---
CELERY_BROKER_URL = 'redis://redis:6379/0'  # Aponta para o serviço 'redis' do docker-compose
CELERY_RESULT_BACKEND = 'django-db' # Salva os resultados no banco de dados Django
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# --- FIM DA CONFIGURAÇÃO DO CELERY ---